#cloud-config
# Add groups to the system
# The following example adds the ubuntu group with members foo and bar and
# the group cloud-users.
hostname: testvm1
groups:
  - cloud-users

# Add users to the system. Users are added after groups are added.
users:
  - name: cloud
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: cloud-users
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC44Al/UL4HppkHuWlSqQkykGpGeWRE/UGGxuYgCSW0Zu594ME5+MKKFJfa/WZhnVMjW3YA2Sa7GxJtDtmAd0alMbtE8m7p3bR5s2HZzKwb7jcXgk2vSJJ1W02fnZFqfihsJj2ViklUlU+ZIO0iqsy1TkR/fgHD1Y38YO8ZrZurJX4sYq9Scm5WSR59wyFzuPfrjzzc0ezG6TI0kArYQGBYDI1JqWqQ8OL7ehIHTpgbOnZo44T+bkDegaWECzTELdHEM9R0hxEGfZui2hW1CsQl3jWI0XHygkYe01awPfgt3Th93Kp+nvBK220HTdcqCNUMGcqU+ANSw2GrWbfE3COF hyungsok@HYUNGSOK-M-M24P"

ipaddr:
  - name : eno16777984
    mode : static
    address : 10.72.86.231/24
    gateway : 10.72.86.1
